services:
  app-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-manager
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html
    depends_on:
      - db-manager
    networks:
      - costManager

  server-manager:
    image: nginx:latest
    container_name: server-manager
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-manager
    networks:
      - costManager

  db-manager:
    image: mysql:8
    container_name: db-manager
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - costManager

volumes:
  dbdata:

networks:
  costManager:
